apiVersion: v1
kind: Service
metadata:
  namespace: $local_namespace
  name: svc-$local_deployment_name
  annotations:
    # https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1056#issuecomment-551585078
    alb.ingress.kubernetes.io/healthcheck-path: /api/healthcheck
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '30'
  labels:
    app: svc-$local_deployment_name
    stage: $local_stage
    tier: frontend
spec:
  type: NodePort
  ports:
    - name: http
      port: $local_port
      targetPort: $local_port
      protocol: TCP
  selector:
    app: $local_deployment_name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: $local_namespace
  name: $local_deployment_name
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app: $local_deployment_name
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: $local_deployment_name
        stage: $local_stage
        commit: $local_commit_sha
        version: $local_version
        deploy: template
        tier: frontend
    spec:
      nodeSelector:
        kops.k8s.io/instancegroup: nodesdev
      tolerations:
        - key: dev
          operator: Exists
      terminationGracePeriodSeconds: 30
      containers:
        - name: $local_deployment_name
          image: $local_image_endpoint/$local_image_name:$local_image_tag
          imagePullPolicy: 'Always'
          ports:
            - containerPort: $local_port
          resources:
            limits:
              cpu: '200m'
              memory: '400Mi'
            requests:
              cpu: '200m'
              memory: '300Mi'
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/readiness
              port: $local_port
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              path: /api/healthcheck
              port: $local_port
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
            initialDelaySeconds: 30
