---
apiVersion: v1
kind: Pod
metadata:
  namespace: sandbox
  name: dev-guipodtest
spec:
  nodeSelector:
    kops.k8s.io/instancegroup: nodesdev
  tolerations:
    - key: dev
      operator: Exists
  volumes:
    - name: secret-common
      secret:
        secretName: dev-secret-common
  containers:
    - name: dev-guipodtest
      image: 314916389090.dkr.ecr.ap-northeast-2.amazonaws.com/vling_gui_v2:sandbox1
      imagePullPolicy: 'Always'
      volumeMounts:
        - mountPath: '/usr/src/app/secret'
          name: secret-common
          readOnly: true
      command: ['/bin/sh', '-c']
      args:
        - >-
          sleep 36000;
      resources:
        limits:
          cpu: '2000m'
          memory: '2500Mi'
        requests:
          cpu: '100m'
          memory: '1500Mi'
