FROM node:16-alpine

RUN apk update
RUN apk add --no-cache bash
RUN apk add --no-cache libc6-compat

WORKDIR /usr/src/app

# sh에서 환경변수와 public, scripts, config 등 파일을 만든 후 standalone만 가져옵니다.
COPY .next/standalone/ ./

# 당신의 workspace 경로를 입력하시오
WORKDIR /usr/src/app/vling/post

# next.js 를 사용한다면 아래를 활성화 하기 바람
RUN npm install sharp@0.32.6 

CMD [ "npm", "run", "dist", "--", "prod"]