FROM node:16-alpine

RUN apk update
RUN apk add --no-cache bash
RUN apk add --no-cache libc6-compat

WORKDIR /usr/src/app

# sh에서 환경변수와 public, scripts, config 등 파일을 만든 후 standalone만 가져옵니다.
COPY .next/standalone/ ./

WORKDIR /usr/src/app/vling/search

RUN npm install sharp@0.32.6 

CMD [ "npm", "run", "dist", "--", "dev"]